---
version: '2'
services:
  sickbeard:
    env_file: ./vars
    build: .
    image: 'paulroche/sickbeard'
    container_name: sickbeard
    restart: 'always'
    ports:
      - "8081:8081"
    cpuset: "0"
    volumes:
      - '/data/sickbeard:/data/sickbeard'
      - '/mediabox:/mediabox'
